/**
 * RashtraBid Domain Models & Constants — JavaScript
 */

export const VerificationStatus = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  REVIEW: 'REVIEW',
  MANUAL_REQUIRED: 'MANUAL_REQUIRED',
};

export const DocType = {
  CA_CERTIFICATE: 'CA_CERTIFICATE',
  GST_CERTIFICATE: 'GST_CERTIFICATE',
  UDYAM_CERTIFICATE: 'UDYAM_CERTIFICATE',
  PAN_CARD: 'PAN_CARD',
  EPFO_CERTIFICATE: 'EPFO_CERTIFICATE',
  MCA_INCORPORATION: 'MCA_INCORPORATION',
  MII_DECLARATION: 'MII_DECLARATION',
  UNKNOWN: 'UNKNOWN',
};

export const RuleResultStatus = {
  PASS: 'PASS',
  FAIL: 'FAIL',
  REVIEW: 'REVIEW',
  PENDING: 'PENDING',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  MISSING: 'MISSING',
  EXPIRED: 'EXPIRED',
};
